### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by jsarenik** [xkollar/handy-haskell#1]
How to use this scripts? Let's say I am a Haskell newbie, found your repo and would like to gain some magician skills by running the scripts... Thanks.

**Comment by xkollar** [comment]
Hello jasan (@jsarenik). I tried to extend documentation a little... mostly description. Would you like some part to be extended more?

**Comment by xkollar** [comment]
Closing for now. Should there be something more you would like me to do, please reopen :-).

**Comment by jsarenik** [comment]
OK, thanks! :-) And good luck!
